# Generated by Django 5.1.2 on 2024-10-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson_course_lesson_description_lesson_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
